services:
  api:
    build:
      context: . # Le contexte est le dossier courant où se trouve le docker-compose.yml
      dockerfile: Dockerfile
    container_name: yoovisit-api
    restart: on-failure
    ports:
      - "8180:8180" # Mappe le port 8180 de ta machine au port 8180 de l'API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8180
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=YooVisit_Users;Username=yoovisit;Password=MonMotDePasseSuperSecurise!123
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    container_name: yoovisit-postgres
    restart: always
    environment:
      - POSTGRES_USER=yoovisit
      - POSTGRES_PASSWORD=MonMotDePasseSuperSecurise!123
      - POSTGRES_DB=YooVisit_Users
    # La section cruciale, correctement indentée :
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: